concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  revapi:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      run: 'echo "Using the old version tag, as per git describe, of $(git describe)";

        '
    - continue-on-error: true
      run: ./gradlew revapi --rerun-tasks
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test logs
        path: '**/build/testlogs

          '
name: API Binary Compatibility Checks
on:
  repository_dispatch:
    types: trigger-ga___api-binary-compatibility.yml
