concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  hive2-tests:
    env:
      SPARK_LOCAL_IP: localhost
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.jvm }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: ${{ runner.os }}-gradle-
    - continue-on-error: true
      run: echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/
        -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
    - continue-on-error: true
      run: ./gradlew -DsparkVersions= -DhiveVersions=2 -DflinkVersions= -Pquick=true
        :iceberg-mr:check :iceberg-hive-runtime:check -x javadoc
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test logs
        path: '**/build/testlogs

          '
    strategy:
      matrix:
        jvm:
        - 8
        - 11
        - 17
  hive3-tests:
    env:
      SPARK_LOCAL_IP: localhost
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.jvm }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: ${{ runner.os }}-gradle-
    - continue-on-error: true
      run: echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/
        -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
    - continue-on-error: true
      run: ./gradlew -DsparkVersions= -DhiveVersions=3 -DflinkVersions= -Pquick=true
        :iceberg-hive3-orc-bundle:check :iceberg-hive3:check :iceberg-hive-runtime:check
        -x javadoc
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test logs
        path: '**/build/testlogs

          '
    strategy:
      matrix:
        jvm:
        - 8
        - 11
        - 17
name: Hive CI
on:
  repository_dispatch:
    types: trigger-ga___hive-ci.yml
