concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  build-checks:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: ./gradlew -DallModules build -x test -x javadoc -x integrationTest
  build-javadoc:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: ./gradlew -Pquick=true javadoc
  core-tests:
    env:
      SPARK_LOCAL_IP: localhost
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: ${{ matrix.jvm }}
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: ${{ runner.os }}-gradle-
    - continue-on-error: true
      run: echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/
        -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
    - continue-on-error: true
      run: ./gradlew check -DsparkVersions= -DhiveVersions= -DflinkVersions= -Pquick=true
        -x javadoc
    - continue-on-error: true
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test logs
        path: '**/build/testlogs

          '
    strategy:
      matrix:
        jvm:
        - 8
        - 11
        - 17
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___java-ci.yml
