jobs:
  triage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: true
name: Pull Request Labeler
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
permissions:
  contents: read
  pull-requests: write
