jobs:
  rat:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      run: 'dev/check-license

        '
name: Run License Check
on:
  repository_dispatch:
    types: trigger-ga___license-check.yml
