concurrency:
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  openapi-spec-validator:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - continue-on-error: true
      name: Install
      run: make install
      working-directory: ./open-api
    - continue-on-error: true
      name: Validate REST catalog spec
      run: make lint
      working-directory: ./open-api
    - continue-on-error: true
      name: Generate REST catalog spec Python code
      run: make generate
      working-directory: ./open-api
    - continue-on-error: true
      name: Check if code is up to date
      run: git diff --exit-code
      working-directory: ./open-api
    - continue-on-error: true
      name: Validate S3 REST Signer spec
      run: openapi-spec-validator s3-signer-open-api.yaml
      working-directory: ./aws/src/main/resources
name: Open-API
on:
  repository_dispatch:
    types: trigger-ga___open-api.yml
