jobs:
  publish-snapshot:
    if: github.repository_owner == 'apache'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: './gradlew printVersion

        ./gradlew -DallModules publishApachePublicationToMavenRepository -PmavenUser=${{
        secrets.NEXUS_USER }} -PmavenPassword=${{ secrets.NEXUS_PW }}

        ./gradlew -DflinkVersions= -DsparkVersions=3.3,3.4,3.5 -DscalaVersion=2.13
        -DhiveVersions= publishApachePublicationToMavenRepository -PmavenUser=${{
        secrets.NEXUS_USER }} -PmavenPassword=${{ secrets.NEXUS_PW }}

        '
name: Publish Snapshot to Maven
on:
  repository_dispatch:
    types: trigger-ga___publish-snapshot.yml
