jobs:
  run-benchmark:
    env:
      SPARK_LOCAL_IP: localhost
    if: github.repository_owner == 'apache'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.ref }}
        repository: ${{ github.event.inputs.repo }}
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')
          }}
        path: '~/.gradle/caches

          ~/.gradle/wrapper

          '
        restore-keys: ${{ runner.os }}-gradle-
    - continue-on-error: true
      run: echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/
        -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
    - continue-on-error: true
      name: Run Benchmark
      run: ./gradlew :iceberg-spark:${{ matrix.spark_version }}:jmh -PjmhIncludeRegex=${{
        matrix.benchmark }} -PjmhOutputPath=benchmark/${{ matrix.benchmark }}.txt
        -PjmhJsonOutputPath=benchmark/${{ matrix.benchmark }}.json
    - continue-on-error: true
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: '**/benchmark/*

          '
    strategy:
      fail-fast: false
      matrix:
        benchmark:
        - SparkParquetReadersFlatDataBenchmark
        - SparkParquetReadersNestedDataBenchmark
        - SparkParquetWritersFlatDataBenchmark
        - SparkParquetWritersNestedDataBenchmark
        - IcebergSourceFlatParquetDataFilterBenchmark
        - IcebergSourceFlatParquetDataReadBenchmark
        - IcebergSourceFlatParquetDataWriteBenchmark
        - IcebergSourceNestedListParquetDataWriteBenchmark
        - IcebergSourceNestedParquetDataFilterBenchmark
        - IcebergSourceNestedParquetDataReadBenchmark
        - IcebergSourceNestedParquetDataWriteBenchmark
        - IcebergSourceParquetEqDeleteBenchmark
        - IcebergSourceParquetMultiDeleteFileBenchmark
        - IcebergSourceParquetPosDeleteBenchmark
        - IcebergSourceParquetWithUnrelatedDeleteBenchmark
        spark_version:
        - iceberg-spark-3.5
name: Recurring JMH Benchmarks
on:
  repository_dispatch:
    types: trigger-ga___recurring-jmh-benchmarks.yml
