jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - continue-on-error: true
      name: Deploy Iceberg documentation
      run: 'git config --global user.name ''GitHub Actions''

        git config --global user.email ''actions@github.com''

        make deploy

        '
      working-directory: ./site
name: site-ci
on:
  repository_dispatch:
    types: trigger-ga___site-ci.yml
