jobs:
  stale:
    if: github.repository_owner == 'apache'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9.0.0
      with:
        ascending: true
        close-issue-message: 'This issue has been closed because it has not received
          any activity in the last 14 days since being marked as ''stale''

          '
        close-pr-message: This pull request has been closed due to lack of activity.
          This is not a judgement on the merit of the PR in any way. It is just a
          way of keeping the PR queue manageable. If you think that is incorrect,
          or the pull request requires review, you can revive the PR at any time.
        days-before-issue-close: 14
        days-before-issue-stale: 180
        days-before-pr-close: 7
        days-before-pr-stale: 30
        exempt-issue-labels: not-stale
        exempt-pr-labels: not-stale,security
        operations-per-run: 100
        stale-issue-label: stale
        stale-issue-message: 'This issue has been automatically marked as stale because
          it has been open for 180 days with no activity. It will be closed in next
          14 days if no further activity occurs. To permanently prevent this issue
          from being considered stale, add the label ''not-stale'', but commenting
          on the issue is preferred when possible.

          '
        stale-pr-label: stale
        stale-pr-message: "This pull request has been marked as stale due to 30 days\
          \ of inactivity. It will be closed in 1 week if no further activity occurs.\
          \ If you think that\u2019s incorrect or this pull request requires a review,\
          \ please simply write any comment. If closed, you can revive the PR at any\
          \ time and @mention a reviewer or discuss it on the dev@iceberg.apache.org\
          \ list. Thank you for your contributions."
name: Close Stale Issues and PRs
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
permissions:
  issues: write
